/// Authoritative protected-local MODEL-13 presentation output; presentation typing and labels only.
table 'Seed Context'
	lineageTag: fe54f3fe-10d5-5f0f-9d13-002a6c8a83f6

	column 'Protected Physical Location ID'
		dataType: string
		isHidden
		lineageTag: 38ed46f5-17bd-5c8e-828e-4cc209c5811c
		summarizeBy: none
		sourceColumn: Protected Physical Location ID

		annotation SummarizationSetBy = Automatic

	column 'Latitude'
		dataType: double
		formatString: 0.00
		lineageTag: 4db0d3c9-36be-5f3a-b30f-16cc7b3aaeb2
		summarizeBy: none
		sourceColumn: Latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column 'Longitude'
		dataType: double
		formatString: 0.00
		lineageTag: 5d677509-2d54-5546-ba51-9e8c8e1f8333
		summarizeBy: none
		sourceColumn: Longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column 'Mean Isolated Sales'
		dataType: double
		formatString: 0.00
		lineageTag: 74773558-0501-5d15-a80c-a3b1a9d8f45c
		summarizeBy: none
		sourceColumn: Mean Isolated Sales

		annotation SummarizationSetBy = Automatic

	column 'Frozen MODEL-12 Prediction'
		dataType: double
		formatString: 0.00
		lineageTag: cefdb1db-22d0-55a0-b633-5f2e791a27c7
		summarizeBy: none
		sourceColumn: Frozen MODEL-12 Prediction

		annotation SummarizationSetBy = Automatic

	column 'Successor OOF Prediction'
		dataType: double
		formatString: 0.00
		lineageTag: 107d0f8e-1212-54d5-9271-9dfd545aef2c
		summarizeBy: none
		sourceColumn: Successor OOF Prediction

		annotation SummarizationSetBy = Automatic

	column 'Successor OOF Absolute Log Error'
		dataType: double
		formatString: 0.00
		lineageTag: 7c85bb3a-c4f7-5fca-bf9e-04b938d4848e
		summarizeBy: none
		sourceColumn: Successor OOF Absolute Log Error

		annotation SummarizationSetBy = Automatic

	column 'Household Opportunity'
		dataType: double
		formatString: 0.00
		lineageTag: e5d638bb-8860-52a8-a9ed-d97f6b7d6494
		summarizeBy: none
		sourceColumn: Household Opportunity

		annotation SummarizationSetBy = Automatic

	column 'Customer Fit'
		dataType: double
		formatString: 0.00
		lineageTag: 6628af69-74f6-5856-95fe-db039f97ba7a
		summarizeBy: none
		sourceColumn: Customer Fit

		annotation SummarizationSetBy = Automatic

	column 'Modeled Target Mass'
		dataType: double
		formatString: 0.00
		lineageTag: 8553ecd5-67cf-53a2-9b9c-9b3565938dfa
		summarizeBy: none
		sourceColumn: Modeled Target Mass

		annotation SummarizationSetBy = Automatic

	column 'Support Truncation'
		dataType: boolean
		lineageTag: c642ce8f-b45a-515a-a72e-38281756e089
		summarizeBy: none
		sourceColumn: Support Truncation

		annotation SummarizationSetBy = Automatic

	column 'QA Status'
		dataType: string
		lineageTag: f8537ff4-505e-5fbe-851c-37295387998e
		summarizeBy: none
		sourceColumn: QA Status

		annotation SummarizationSetBy = Automatic

	column 'Model Lineage ID'
		dataType: string
		isHidden
		lineageTag: 02415cca-edaa-5946-8057-76015892b6dd
		summarizeBy: none
		sourceColumn: Model Lineage ID

		annotation SummarizationSetBy = Automatic

	partition 'Seed Context' = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("__PBI01_SEED_CSV__"), [Delimiter = ",", Columns = 13, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					#"Renamed Columns" = Table.RenameColumns(#"Promoted Headers", {{"protected_physical_location_id", "Protected Physical Location ID"}, {"latitude", "Latitude"}, {"longitude", "Longitude"}, {"mean_isolated_sales", "Mean Isolated Sales"}, {"frozen_model12_prediction", "Frozen MODEL-12 Prediction"}, {"successor_oof_prediction", "Successor OOF Prediction"}, {"successor_oof_absolute_log_error", "Successor OOF Absolute Log Error"}, {"household_opportunity", "Household Opportunity"}, {"customer_fit_proxy", "Customer Fit"}, {"modeled_target_mass", "Modeled Target Mass"}, {"support_truncation", "Support Truncation"}, {"qa_status", "QA Status"}, {"model_lineage_id", "Model Lineage ID"}}, MissingField.Error),
					#"Typed Columns" = Table.TransformColumnTypes(#"Renamed Columns", {{"Protected Physical Location ID", type text}, {"Latitude", type number}, {"Longitude", type number}, {"Mean Isolated Sales", type number}, {"Frozen MODEL-12 Prediction", type number}, {"Successor OOF Prediction", type number}, {"Successor OOF Absolute Log Error", type number}, {"Household Opportunity", type number}, {"Customer Fit", type number}, {"Modeled Target Mass", type number}, {"Support Truncation", type logical}, {"QA Status", type text}, {"Model Lineage ID", type text}}, "en-US")
				in
					#"Typed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
